lexik_jwt_authentication:
  user_identity_field: username
  secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # required for token creation
  public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # required for token verification
  pass_phrase:      'lalalala' # required for token creation, usage of an environment variable is recommended
  token_ttl:        3600 #One hour