version: '3.7'

services:
    back-front:
        build: ./back-front
        working_dir: /var/www/html/
        environment:
            docker: "true"
        ports:
            - 8000:8080
        volumes:
            - ./back-front:/var/www/html
            - /var/www/html/node_modules
            - /var/www/html/public/build
            - /var/www/html/vendor
    back:
        build: ./back/
        working_dir: /var/www/html/
        environment:
            docker: "true"
        ports:
            - 8001:8080 
        volumes:
            - ./back/:/var/www/html
            - /var/www/html/vendor
            - /var/www/html/config/jwt
