version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        build: ./back-front/
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8080:8080
        volumes:
            - ./back-front/:/var/www
            - logs:/var/www/logs
            - /var/www/node_modules
