list_users: #done
  path: /users
  methods: [GET]
  controller: App\Application\Actions\User\ListUsersAction::action
view_user: #done
  path: /users/{username}
  methods: [GET]
  controller: App\Application\Actions\User\ViewUserAction::action
delete_user: #done
  path: /users/{username}
  methods: [DELETE]
  controller: App\Application\Actions\User\DeleteUserAction::action
#Todos
list_todos: #done
  path: /todos
  methods: [GET]
  controller: App\Application\Actions\Todo\ListTodosAction::action
create_todo: #done
  path: /todos
  methods: [POST]
  controller: App\Application\Actions\Todo\CreateTodoAction::action
view_todo: #done
  path: /todos/{id}
  methods: [GET]
  controller: App\Application\Actions\Todo\ViewTodoAction::action
delete_todo: #done
  path: /todos/created/{id}
  methods: [DELETE]
  controller: App\Application\Actions\Todo\DeleteTodoAction::action
assign_todo: #TODO - remove
  path: /todos/{id}/assign
  methods: [PATCH]
  controller: App\Application\Actions\Todo\AssignTodoAction::action
update_todo: #TODO
  path: /todos/{id}/update
  methods: [PATCH]
  controller: App\Application\Actions\Todo\UpdateTodoAction::action
comment_todo: #todo: mapping problem
  path: /todos/{id}/comment
  methods: [POST]
  controller: App\Application\Actions\Todo\Comment\AddCommentAction::action
edit_comment: #todo
  path: /todos/{id}/comment
  methods: [PUT]
  controller: App\Application\Actions\Todo\Comment\EditCommentTodoAction::action
