#Users
signup:
    path: /signup
    controller: App\Application\Actions\User\CreateUserAction::action
    methods: [POST]
api_login_check:
    path: /api/login_check
#TODO: add logout
app_file:
    prefix: api
    resource: '../src/Application/Resources/config/routes.yaml'
